---
# Setup a Docker node

- include: redhat.yml
  when: ansible_distribution == 'RedHat'

- name: docker | setup repository
  become: true
  get_url:
    dest: /etc/yum.repos.d/docker-ce.repo
    url: https://download.docker.com/linux/centos/docker-ce.repo

- name: docker | install docker
  become: true
  yum:
    pkg: >
      docker-ce{{ (docker_version | length > 0) |
      ternary('-' + docker_version, '') }}
    state: present

- name: docker | setup lvm docker-pool
  become: true
  lvol:
    vg: "{{ docker_vgname }}"
##    lv: docker-pool
    lv: "{{ lvm_lvname }}"
    size: "{{ docker_poolsize }}"
    opts: >
      {{ docker_lvopts | default(None) }} --thin --poolmetadatasize
      {{ docker_metadatasize }}
  when: docker_use_custom_storage

- name: docker | configuration directory
  become: true
  file:
    path: /etc/docker
    state: directory

# https://docs.docker.com/engine/reference/commandline/dockerd/#linux-configuration-file
- name: docker | configure docker options
  become: true
  template:
    src: etc-docker-daemon-json.j2
    dest: /etc/docker/daemon.json
    backup: true
  notify:
    - restart docker

- name: docker | enable
  become: true
  service:
    name: docker
    state: started
    enabled: true
  when: docker_systemd_setup

- name: docker | group members
  become: true
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: "{{ docker_groupmembers }}"
