---
# RHEL specific tasks

# RHEL system needs extra repositories for docker
- name: docker | check if rhel-7-server-extras-rpms repo enabled
  become: true
  command: subscription-manager repos --list-enabled
  register: _subscription_manager_repos
  check_mode: false
  changed_when: >-
    'rhel-7-server-extras-rpms' not in _subscription_manager_repos.stdout

- name: docker | enable rhel-7-server-extras-rpms repo
  become: true
  command: subscription-manager repos --enable=rhel-7-server-extras-rpms
  when: "'rhel-7-server-extras-rpms' not in _subscription_manager_repos.stdout"
