---
# Crea La net in base alla scelta effettuata sul prompt


- community.libvirt.virt_net:
#    state: present
    command: status
    name: "{{ lib_net.br_net }}"
  register: vm_net_state
  ignore_errors: yes
- debug:
    msg: "{{ vm_net_state }}"


- name: make XML net file
  copy:
    dest: "/tmp/kvmNAT.xml"
    content: |
      <network>
        <name>{{ lib_net.br_net }}</name>
        <bridge name="{{ lib_net.br_if }}"/>
        <forward mode="nat"/>
        <ip address="{{ lib_net.br_net_gw }}" netmask="{{ lib_net.br_net_mask }}">
        </ip>
      </network>
  when: vm_net_state is failed and lib_net.br_net is defined and lib_net.br_if != 'null' 


- name: Define NET
  become: yes
  command: "virsh net-define --file /tmp/{{ lib_net.br_net }}.xml"
##  command: "virsh net-{{ item }}"
##  with_items:
##  - define --file /tmp/kvmNAT.xml
  when: vm_net_state is failed and lib_net.br_net is defined and lib_net.br_if != 'null' 

- name: set autostart NET
  community.libvirt.virt_net:
    autostart: yes
    name: "{{ lib_net.br_net }}"
  when: vm_net_state is failed and lib_net.br_net is defined and lib_net.br_if != 'null' 

- name: Start NET
  community.libvirt.virt_net:
    command: start 
    name: "{{ lib_net.br_net }}"
  when: vm_net_state is failed and lib_net.br_net is defined

- name: Stato NET
  community.libvirt.virt_net:
    command: status
    name: "{{ lib_net.br_net }}"
  when: lib_net.br_net is defined and lib_net.br_if != 'null'


- name: chknet | Se la rete non viene creata lo indica
  ansible.builtin.debug:
    msg: 'Rete KVM non Creata da Template'
  when: lib_net.br_net is defined and lib_net.br_if != 'null'

- name: chkip | Avvisa che non è stato adottato l'IP di template
  debug:
    msg: Template Network 192.168.123.1 Non Definita
  when: lib_net.br_net_gw != '192.168.123.1'
