---

## Non mi funziona il plugin lookup :(
#- name: Variabile br_net
#  debug:
#    msg: VAR = {{ vg.vgname }}
#  loop: "{{ vg_groups }}"
#  loop_control:
#    loop_var: vg


- name: include tasks di creazione VM
  include_tasks: runmake.yml
  when: ansible_os_family == "RedHat" or ansible_os_family == "Debian" 
    
