---
- name: Set VM HOSTS
  become: yes
  delegate_to: localhost
  lineinfile:
    path: "{{ filehosts }}"
    line: "{{ lib_net.ip_address }} {{ lib_vm.vm_name }} #Created by Ansible Automate"

- name: Update Installed Inventory 
  delegate_to: localhost
  lineinfile:
    path: "{{ hoststarget }}"
    insertbefore: ^[vm]
    line: "{{ lib_vm.vm_name }} ansible_host={{ lib_net.ip_address }}"
    create: yes

