# tasks file for ansible-role-kvm-operate

- name: Check if kind and operate are defined
  fail:
   msg: "Mandatory Parameters needed: kind & operate"
  when:
  - kind is undefined
  - operate is undefined

- name: VM Clone
  import_tasks: vm-clone.yml
  when: kind == 'vm' and operate == 'clone'

- name: VM Operate
  import_tasks: vm-ops.yml
  when: kind == 'vm' and operate != 'clone'

- name: Storage Operate
  import_tasks: storage.yml
  when: kind == 'storage'
